apiVersion: v1
kind: Service
metadata:
  name: kubellm-api
  namespace: kubellm
  labels:
    app.kubernetes.io/name: kubellm-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: kubellm
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: kubellm-api